services:
  rabbitmq:
    build:
      context: .
      dockerfile: dockerfile
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
      - tickets_network
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    - rabbitmq_logs:/var/log/rabbitmq

volumes:
  rabbitmq_data:
  rabbitmq_logs:

networks:
  tickets_network:
    external: true