services: 
    postgres:
        image: postgres:16.4
        container_name: postgres
        hostname: postgres
        networks:
            - tickets_network
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "observer"
            POSTGRES_PASSWORD: "password"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./init-db:/docker-entrypoint-initdb.d
            - tickets-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        mem_limit: 512M
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U observer -d $POSTGRES_DB"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        command: ["postgres", "-c", "wal_level=logical"]

volumes:
    tickets-data:

networks:
  tickets_network:
    external: true